version: 0.2

phases:
  check_node:
    commands:
      - node -v
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist